### PR TITLE
Issue #16 cx v0.6.0

### PR DESCRIPTION
**Pull request by BigOokie**
Fixes #
Update skycoin-cx formula to support v0.6.0

Changes:
- skycoin-cx.rb now points to the v0.6.0 release of CX
- updated Readme.md to include steps for contributors to test changes to formula locally (prior to submitting PR)

Does this change need to mentioned in CHANGELOG.md?

Yes

### CODE REVIEW

**Comment by BigOokie** [comment]
> @BigOokie the result I mean , let's wait for it to finish in green before merge

Lol.  Sorry was just letting you know i've submitted the PR. Certainly want Travis to give it the green light.

**Comment by olemis** [comment]
@BigOokie lol

**Comment by BigOokie** [comment]
Looks like Travis failed with a timeout of some sort.
Doesn’t look to be related to my PR...

**Comment by olemis** [comment]
@BigOokie will fix that later

**Comment by olemis** [comment]
fixed in a622247

**Pull request closed without merging**
